### PR TITLE
stability and maintenance

### PR DESCRIPTION
**Pull request by hiro5id**
## Description of changes

* Upgrade node from v12 to v16
* Whenever a image processing attempt fails, retry at least 2 more times before giving up. This is to avoid losing notifications due to occasional blips during the Ai identification process.
* Added readme documentation to describe how to manually publish your own version of this project to docker hub.

## Checklist

If your change touches anything under src or the README.md file
these items must be done:

- [x] User-facing change description added to unreleased section of CHANGELOG.md

### CODE REVIEW

**Comment by hiro5id** [comment]
closing.... I should have read the contribution readme, to create pull requests using feature branch

**Comment by neilenns** [comment]
@hiro5id Thanks for the contribution. When you open your next PR please open three issues for the three things you are addressing and do one fix in each PR (three total). Thanks!

**Comment by hiro5id** [comment]
I'm not sure how to do that easily @neilenns .  I am making a lot of improvements but they depend on each other, and I don't want to have to wait for each PR to be accepted before I can build on top of it to submit the next PR.  I am trying to fix some deficiencies for myself, and I am more than happy to contribute my changes back.  But I don't know how to split them up into separate PR's without taking weeks of back and forth.

Perhaps I can consolidate each logical change into separate commits, but all in one PR ?  I don't know i'll have a look what I can do.

**Comment by neilenns** [comment]
@hiro5id You have separate feature branches for each improvement you want to make, and have to wait for the PRs to be accepted if there are dependencies. This PR didn't have any, it was three independent things that could be opened and merged concurrently.

Also there have to be issues logged for the changes first, so I know what is coming and we can discuss the approach (if appropriate) to resolving them.

**Pull request closed without merging**
